import type { TestQuestion } from "../testTypes";

// Test 04 rebuilt directly from the uploaded NPTEL HTML source.
// Math is preserved from the source's TeX annotations.
// Expected answers are preserved only where the source explicitly exposes them.
// Image-based options are represented by their source image path because the saved HTML did not include the image files.

const test04Questions: TestQuestion[] = [
  {
    id: 1,
    marks: 2,
    type: "MSQ",
    question: "A contract is to be completed in 52 days and 125 identical robots were employed, each operational for 7 hours a day. After 39 days, five-seventh of the work was completed. How many additional robots would be required to complete the work on time, if each robot is now operational for 8 hours a day?",
    options: [
      "50",
      "89",
      "146",
      "175",
    ],
    answer: [
      "A",
      "B",
      "C",
      "D",
    ],
  },
  {
    id: 2,
    marks: 2,
    type: "MCQ",
    question: "The number of 3-digit numbers such that the digit 1 is never to the immediate right of 2 is____",
    options: [
      "781",
      "791",
      "881",
      "891",
    ],
    answer: "A",
  },
  {
    id: 3,
    marks: 1,
    type: "MCQ",
    question: "Fatima starts from point P. goes North for 3 km. and then East for 4 km to reach point Q. She then turns to face point P and goes 15 km in that direction. She then goes North for 6 km. How far is she from point P. and in which direction should she go to reach point P?",
    options: [
      "8 km. East",
      "12 km, North",
      "6 km, East",
      "10 km, North",
    ],
    answer: "A",
  },
  {
    id: 4,
    marks: 2,
    type: "MCQ",
    question: "In a country of 1400 million population, 70% own mobile phones. Among the mobile phone owners, only 294 million access the Internet. Among these Internet users, only half buy goods from e-commerce portals. What is the percentage of these buyers in the country?",
    options: [
      "10.50",
      "14.70",
      "15.00",
      "50.00",
    ],
    answer: "A",
  },
  {
    id: 5,
    marks: 2,
    type: "MCQ",
    question: "\"If you are looking for a history of India, or for an account of the rise and fall of the British Raj, or for the reason of the cleaving of the subcontinent into two mutually antagonistic parts and the effects this mutilation will have in the respective sections, and ultimately on Asia, you will not find it in these pages, for though I have spent a lifetime in the country. I lived too near the seat of events, and was too intimately associated with the actors, to get the perspective needed for the impartial recording of these matters.\" Which of the following statements best reflects the author's opinion?",
    options: [
      "An intimate association does not allow for the necessary perspective.",
      "Matters are recorded with an impartial perspective.",
      "An intimate association offers an impartial perspective.",
      "Actors are typically associated with the impartial recording of matters.",
    ],
    answer: "A",
  },
  {
    id: 6,
    marks: 1,
    type: "MCQ",
    question: "It is __________to read this year's textbook ___________the last year's.",
    options: [
      "easier, than",
      "most easy, than",
      "easier. from",
      "easiest, from",
    ],
    answer: "A",
  },
  {
    id: 7,
    marks: 2,
    type: "MCQ",
    question: "Some people suggest anti-obesity measures (AOM) such as displaying calorie information in restaurant menus. Such measures sidestep addressing the core problems that cause obesity: poverty and income inequality, Which one of the following statements summarizes the passage?",
    options: [
      "The proposed AOM addresses the core problems that cause obesity.",
      "If obesity reduces, poverty will naturally reduce, since obesity causes poverty.",
      "AOM are addressing the core problems and are likely to succeed.",
      "AOM are addressing the problem superficially.",
    ],
    answer: "D",
  },
  {
    id: 8,
    marks: 1,
    type: "MCQ",
    question: "The value of the expression \\(\\frac{1}{1 + log_{u} vw} + \\frac{1}{1 + log_{v} wu} + \\frac{1}{1 + log_{w} uv}\\) is ________.",
    options: [
      "-1",
      "0",
      "1",
      "3",
    ],
    answer: "C",
  },
  {
    id: 9,
    marks: 1,
    type: "MCQ",
    question: "Given below are two statements and four conclusions drawn based on the statements. Statement 1: Some bottles are cups. Statement 2: All cups are knives. Conclusion I: Some bottles are knives. Conclusion II: Some knives are cups. Conclusion III: All cups are bottles. Conclusion IV: All knives are cups. Which one of the following options can be logically inferred?",
    options: [
      "Only conclusion I and conclusion II are correct",
      "Only conclusion II and conclusion III are correct",
      "Only conclusion II and conclusion IV are correct",
      "Only conclusion III and conclusion IV are correct",
    ],
    answer: "A",
  },
  {
    id: 10,
    marks: 1,
    type: "MCQ",
    question: "",
    options: [
      "[IMAGE: ./Courses __ NPTEL01_files/GATE_2021_GA_04_01.png]",
      "[IMAGE: ./Courses __ NPTEL01_files/GATE_2021_GA_04_02.png]",
      "[IMAGE: ./Courses __ NPTEL01_files/GATE_2021_GA_04_03.png]",
      "[IMAGE: ./Courses __ NPTEL01_files/GATE_2021_GA_04_04.png]",
    ],
    answer: "A",
  },
  {
    id: 11,
    marks: 2,
    type: "NAT",
    question: "The rate of change of f (x, y, z) = x + x cos z − y sin z + y at \\(\\text{P}_{0}\\) in the direction from \\(\\text{P}_{0}\\) (2, −1, 0) to \\(\\text{P}_{1}\\) (0, 1, 2) is ________.",
    answer: "0",
  },
  {
    id: 12,
    marks: 2,
    type: "NAT",
    question: "Let \\(D\\) be the region in \\(R^2\\) bounded by the parabola \\(y^2 =x\\) and the line \\(y=x.\\) Then \\(\\int \\int_D 3xy dx dy\\) equals ___________.",
    answer: "2 to 2",
  },
  {
    id: 13,
    marks: 2,
    type: "NAT",
    question: "The surface area of the paraboloid \\(z = x^{2} + y^{2}\\) between the planes z = 0 and z = 1 is ___________ (round off to ONE decimal place).",
    answer: { min: 5.1, max: 5.5 },
  },
  {
    id: 14,
    marks: 2,
    type: "NAT",
    question: "Let D = { \\((x, y) \\in \\text{ R}^{2} : 1 \\leq x \\leq 1000, 1 \\leq y \\leq 1000\\) }. Define \\(f(x,y) = \\frac{xy}{2} + \\frac{500}{x} + \\frac{500}{y}\\) . Then the minimum value of f on D is equal to ________.",
    answer: "150",
  },
  {
    id: 15,
    marks: 1,
    type: "NAT",
    question: "Let \\(f : R^2 \\rightarrow R\\) be differentiable. Let \\(D_uf(0, 0) \\text { and } D_vf (0,0)\\) be the directional derivatives of f at \\((0,0)\\) in the directions of the unit vectors \\(u= \\big(\\frac{1}{\\sqrt 5},\\frac{2}{\\sqrt 5}\\big) \\text { and } v\\big(\\frac{1}{\\sqrt 2},\\frac{-1}{\\sqrt 2}\\big),\\) respectively. If \\(D_uf (0,0) = \\sqrt 5 \\text { and } D_v,f(0,0) = \\sqrt 2,\\text { then } \\frac{\\partial f}{\\partial x}(0,0)+ \\frac{\\partial f}{\\partial y} (0,0) =\\)",
    answer: "4 to 4",
  },
  {
    id: 16,
    marks: 1,
    type: "NAT",
    question: "If for some α ∈ R, \\(\\int_1^4 \\int_{-x}^{x} \\frac{ 1}{ x^{2} + y^{2}} dydx = \\int_{\\frac{-\\pi}{4}}^{\\frac{\\pi}{4}} \\int_{sec\\theta}^{\\alpha sec\\theta} \\frac{1}{r} drd\\theta\\) , then the value of α equals _______.",
    answer: "4",
  },
  {
    id: 17,
    marks: 1,
    type: "NAT",
    question: "Let L denote the value of the line integral \\(\\oint_C (3 x - 4 x^{2} y) dx + (4 x y^{2} + 2 y) dy\\) , where C , a circle of radius 2 with centre at origin of the xy -plane, is traversed once in the anti-clockwise direction. Then \\(\\frac{L}{\\pi}\\) is equal to _______.",
    answer: { min: 31.9, max: 32.1 },
  },
  {
    id: 18,
    marks: 2,
    type: "NAT",
    question: "The coefficient of \\((x-1)^5\\) in the Taylor expansion about \\(x=1\\) of the function \\(F(x)= \\displaystyle\\int_1^x \\frac{\\text {log}_e t}{t-1} dt, 0 < x < 2\\) is _____________ (correct upto two decimal places)",
    answer: "0.04 to 0.04",
  },
  {
    id: 19,
    marks: 2,
    type: "MCQ",
    question: "Let M be a 3×3 real symmetric matrix with eigenvalues 0, 2 and a with the respective eigenvectors u = (4,b,c) \\(^{T}\\) , v = (−1,2,0) \\(^{T}\\) and w = (1,1,1) \\(^{T}\\) . Consider the following statements: I. a + b - c = 10. II. The vector x = \\((0, \\frac{3}{2}, \\frac{1}{2})^{T}\\) satisfies Mx = v + w. III. For any d ∈ span {u, v, w}, Mx = d has a solution. IV. The trace of the matrix M \\(^{2}\\) + 2M is 8. (y \\(^{T}\\) denotes the transpose of the vector y) Which of the above statements are TRUE?",
    options: [
      "I, II and III only",
      "I and II only",
      "II and IV only",
      "III and IV only",
    ],
    answer: "B",
  },
  {
    id: 20,
    marks: 2,
    type: "NAT",
    question: "Let \\(V \\big\\{p : p(x)= a_0 + a_1x + a_2x^2, a_0, a_1, a_2 \\in R\\big\\}\\) be the vector space of all polynomials of degree at most 2 over the real field \\(R. \\text { Let } T:V \\rightarrow V\\) be the linear operator given by \\(T(p) = (p(0)- p(1))+(p(0) + p(1)) x + p(0) x^2.\\) Then the sum of the eigenvalues of T is ___________.",
    answer: "1 to 1",
  },
  {
    id: 21,
    marks: 1,
    type: "MCQ",
    question: "Suppose that M is a 5 x 5 matrix with real entries and p(x) = det(xl-M). Then",
    options: [
      "p(0) = det(M)",
      "every eigenvalue of M is real if p(1) + p(2) =0=p(2) + p(3)",
      "\\(M^{-1}\\) is necessarily a polynomial in M of degree 4 if M is invertible.",
      "M is not invertible if \\(M^2- 2M = 0\\)",
    ],
    answer: "C",
  },
  {
    id: 22,
    marks: 1,
    type: "MCQ",
    question: "Suppose that the characteristic equation of \\(M \\in C^{3×3}\\) is \\(\\lambda^{3} + \\alpha \\lambda^{2} + \\beta \\lambda − 1 = 0\\) , where \\(\\alpha, \\beta \\in C\\) with \\(\\alpha + \\beta \\neq 0\\) . Which of the following statements is TRUE?",
    options: [
      "\\(M (I − \\beta M) = M^{−1} (M + \\alpha I)\\)",
      "\\(M (I + \\beta M) = M^{−1} (M - \\alpha I)\\)",
      "\\(M^{−1} (M^{−1} + \\beta I) = M - \\alpha I\\)",
      "\\(M^{−1} (M^{−1} - \\beta I) = M + \\alpha I\\)",
    ],
    answer: "D",
  },
  {
    id: 23,
    marks: 2,
    type: "NAT",
    question: "Let \\(D = \\big\\{z \\in C : |Z| < 2 \\pi \\big\\} \\text { and } f: D \\rightarrow C\\) be the function defined by \\(f(Z) = =\\begin{cases} \\frac{3z^2}{(1 - \\text { cos } z)} & \\text {if} z\\neq 0\\\\6 & \\text { if } z=. 0\\end{cases}\\) If \\(f(z) = \\sum_{n=0}^\\infty a_n z^n \\text { for } z \\in D,\\text { then } 6 a_2\\) = _______",
    answer: "3 to 3",
  },
  {
    id: 24,
    marks: 2,
    type: "MSQ",
    question: "Let T be a \\(\\text{M}\\ddot{\\text{o}}\\text{bius}\\) transformation such that \\(T(0) = \\alpha, T(\\alpha) = 0\\) and \\(T(\\infty) = −\\alpha\\) , where \\(\\alpha = \\frac{(−1 + i)}{\\sqrt{2}}\\) . Let L denote the straight line passing through the origin with slope −1, and let C denote the circle of unit radius centred at the origin. Then, which of the following statements are TRUE?",
    options: [
      "T maps L to a straight line",
      "T maps L to a circle",
      "\\(T^{−1}\\) maps C to a straight line",
      "\\(T^{−1}\\) maps C to a circle",
    ],
    answer: [
      "A",
      "C",
    ],
  },
  {
    id: 25,
    marks: 1,
    type: "MCQ",
    question: "Let f : C → C (the set of all complex numbers) be defined by \\(f(x + iy) = x^{2} + 3 x y^{2} + i (y^{3} + 3 x^{2} y), i = \\sqrt{-1}\\) . Let f'(z) denote the derivative of f with respect to z. Then which one of the following statements is TRUE?",
    options: [
      "f'(1 + i) exists and |f'(1 + i)| = \\(3\\sqrt{5}\\)",
      "f is analytic at the origin",
      "f is not differentiable at i",
      "f is differentiable at 1",
    ],
    answer: "D",
  },
  {
    id: 26,
    marks: 1,
    type: "NAT",
    question: "The number of zeros of the polynomial \\(2 z^{7} − 7 z^{5} + 2 z^{3} − z + 1\\) in the unit disc \\({z \\in \\text{C } : |z| < 1}\\) is ___________.",
    answer: "5",
  },
  {
    id: 27,
    marks: 2,
    type: "MCQ",
    question: "The critical point of the differential equation \\(\\frac{d^2y}{dt^2} + 2 \\alpha \\frac{dy}{dt} + \\beta^2 y =0 ,\\alpha >\\beta >0,\\) is a",
    options: [
      "node and is asymptotically stable.",
      "spiral pont and is asymptotically stable.",
      "node and is unstable.",
      "saddle point and is unstable",
    ],
    answer: "A",
  },
  {
    id: 28,
    marks: 2,
    type: "MCQ",
    question: "The solution to the initial value problem \\(\\frac{d^2y}{dt^2} +2 \\frac{dy}{dt} +5y =3e^{-t} \\text { sin } t, y(0) =0 \\text { and } \\frac{dy}{dt} (0) =3,\\) is",
    options: [
      "\\(y(t) = e^t (\\text { sin } t + \\text { sin } 2t)\\)",
      "\\(y(t) = e^{-t} (\\text { sin } t + \\text { sin } 2t)\\)",
      "\\(y(t) = 3e^t \\text { sin } t\\)",
      "\\(y(t) = 3e^{-t} \\text { sin } t\\)",
    ],
    answer: "B",
  },
  {
    id: 29,
    marks: 2,
    type: "MCQ",
    question: "Let \\(y_1(x)=x^3 \\text { and } y_2(x) = x^2|x| \\text { for } x \\in R.\\) Consider the following statements. (P): \\(y(x) \\text { and } y^2(x)\\) are linearly independent solutions of \\(x^2 \\frac{d^2y}{dx^2}- 4x \\frac{dy}{dx} +6y=0 \\text { on } R.\\) (Q): The Wronskian \\(y_1(x) \\frac{dy_2}{dx} (x)-y_2(x)\\frac{dy_1}{dx}(x)=0 \\text { for all } x \\in R.\\) Which of the above statements hold TRUE?",
    options: [
      "Both P and Q",
      "Only P",
      "Only Q",
      "Neither P nor Q",
    ],
    answer: "A",
  },
  {
    id: 30,
    marks: 1,
    type: "MCQ",
    question: "The eigenvalues of the boundary value problem \\(\\frac{d^2y}{ dx^2} + \\lambda = 0. x \\epsilon (0 ,\\pi) , \\lambda > 0,\\) \\(y(0) = 0, \\lambda(\\pi) - \\frac{dy}{dx} (\\pi) = 0.\\) are given by",
    options: [
      "\\(\\lambda = (n \\pi^2), n= 1,2,3....\\)",
      "\\(\\lambda = n^2, n= 1,2,3....\\)",
      "\\(\\lambda = k_n^2, \\text { where } k_n = 1,2,3....\\) are the roots of \\(k - tan (k\\pi)= 0\\)",
      "\\(\\lambda = k_n^2, \\text { where } k_n = 1,2,3....\\) are the roots of \\(k + tan (k\\pi)= 0\\)",
    ],
    answer: "C",
  },
  {
    id: 31,
    marks: 1,
    type: "NAT",
    question: "If y(x) satisfies the initial value problem \\((x^{2} + y)dx = x dy\\) , y(1) = 2, then y(2) is equal to _______.",
    answer: "6",
  },
  {
    id: 32,
    marks: 1,
    type: "NAT",
    question: "If the differential equation \\(\\frac{dy}{dx} = \\sqrt{x^{2} + y^{2}}, y(1) = 2\\) is solved using the Euler's method with step-size h = 0.1, then y(1.2) is equal to ________ (round off to 2 places of decimal).",
    answer: { min: 2.4, max: 2.5 },
  },
  {
    id: 33,
    marks: 2,
    type: "MCQ",
    question: "For an odd prime p , consider the ring \\(Z[\\sqrt{−p}]\\) = { \\(a + b \\sqrt{−p} : a, b \\in\\) Z} \\(\\subseteq\\) C. Then the element 2 in \\(Z[\\sqrt{−p}]\\) is",
    options: [
      "a unit",
      "a square",
      "a prime",
      "irreducible",
    ],
    answer: "D",
  },
  {
    id: 34,
    marks: 1,
    type: "NAT",
    question: "Let \\(Z_{225}\\) be the ring of integers modulo 225. If x is the number of prime ideals and y is the number of nontrivial units in \\(Z_{225},\\) then \\(x + y\\) is equal to _______________",
    answer: "121 to 121",
  },
  {
    id: 35,
    marks: 1,
    type: "NAT",
    question: "Let \\(G\\) be a non-abelian group of order 125. Then the total number of elements in \\(Z(G) = \\big\\{x\\in G:gx=xg \\text { for all } g \\in G\\big\\}\\) equals _________.",
    answer: "5 to 5",
  },
  {
    id: 36,
    marks: 2,
    type: "NAT",
    question: "Consider \\(C [-1,1]\\) equipped with the supremum norm given by \\(\\parallel f\\parallel_\\infty = \\text { sup } \\big\\{f(t)|:t \\in [-1,1]\\big\\}\\) for \\(f \\in C [-1,1].\\) Define a linear functional T on \\(C [-1,1] \\text { by } T (f) = \\displaystyle\\int_{-1}^0 f(t) dt - \\displaystyle\\int_0^1 f(t)dt \\text { for all } f \\in C[-1,1].\\) Then the value of \\(\\parallel T \\parallel\\) is",
    answer: "1.99 to 2.01",
  },
  {
    id: 37,
    marks: 1,
    type: "NAT",
    question: "Let T: (C[0, 1], || || \\(_{\\infty}\\) ) → R be defined by T(f) = \\(\\int_0^1 2x f(x) dx\\) for all f ∈ C[0, 1]. Then ||T|| is equal to ________.",
    answer: "1",
  },
  {
    id: 38,
    marks: 2,
    type: "MCQ",
    question: "Let \\(X=C^1[0,1].\\) For each \\(f \\in X,\\) define \\(p_1(f):=\\text { sup } \\big\\{|f(t)|: t \\in [0,1]\\big\\}\\) \\(p_2(f):=\\text { sup } \\big\\{|f'(t)|: t \\in [0,1]\\big\\}\\) \\(p_3(f):=p_1(f)+p_2(f).\\) Which of the following statements is TRUE?",
    options: [
      "\\((X,P_1 )\\) is a Banach space",
      "\\((X,P_2 )\\) is a Banach space",
      "\\((X,P_3 )\\) is NOT a Banach space",
      "\\((X,P_3 )\\) does NOT have denumerable basis.",
    ],
    answer: "D",
  },
  {
    id: 39,
    marks: 2,
    type: "NAT",
    question: "Let \\(p(x)\\) be the polynomial of degree at most 2 that interpolates the data \\((-1.2). (0.1) \\text { and } (1.2). \\text { If } q(x)\\) is a polynomial of degree at most 3 such that \\(p(x)+q(x)\\) interpolates the data \\((-1.2). (0,1). (1,2) \\text { and } (2,11). \\text { then } q(3)\\) equals ___________",
    answer: "24 to 24",
  },
  {
    id: 40,
    marks: 2,
    type: "NAT",
    question: "Let p(x) be the polynomial of degree at most 3 that passes through the points (-2, 12), (-1, 1), (0,2) and (2, -8). Then the coefficient of x \\(^{3}\\) in p(x) is equal to _________.",
    answer: "-2",
  },
  {
    id: 41,
    marks: 1,
    type: "NAT",
    question: "If the trapezoidal rule with single interval [0, 1] is exact for approximating the integral \\(\\int_0^1 (x^{3} - cx^{2}) dx\\) , then the value of c is equal to ________.",
    answer: "1.5",
  },
  {
    id: 42,
    marks: 2,
    type: "MCQ",
    question: "If \\(u(x, y)\\) is the solution of the Cauchy problem \\(x \\frac{\\partial u}{\\partial x} + \\frac{\\partial u}{\\partial y} = 1, u(x,0) = -x^2,x > 0 ,\\) then \\(u (2,1)\\) is equal to",
    options: [
      "\\(1 - 2e^{-2}\\)",
      "\\(1 + 4e^{-2}\\)",
      "\\(1 - 4e^{-2}\\)",
      "\\(1 + 2e^{-2}\\)",
    ],
    answer: "C",
  },
  {
    id: 43,
    marks: 2,
    type: "NAT",
    question: "Let u (x, y) be the solution of the first order partial differential equation \\(x \\frac{\\partial u}{\\partial x} + (x^{2} + y) \\frac{\\partial u}{\\partial y} = u\\) , for all x, y ∈ R satisfying u (2, y ) = y − 4, y ∈ R. Then, the value of u (1, 2) is ___________.",
    answer: "1",
  },
  {
    id: 44,
    marks: 2,
    type: "MCQ",
    question: "A solution of the Dirichlet problem \\(\\nabla^{2} u (r, \\theta) = 0, 0 < r < 1, -\\pi \\leq \\theta \\leq \\pi\\) , \\(u (1, \\theta) = |\\theta|, -\\pi \\leq \\theta \\leq \\pi\\) , is given by",
    options: [
      "\\(u (r, \\theta) = \\frac{\\pi}{2} + \\sum_{n=1}^{\\infty} [\\frac{(-1)^{n} - 1}{n^{2}}] r^{n} \\text{ cos }(n\\theta)\\)",
      "\\(u (r, \\theta) = \\frac{2}{\\pi} \\sum_{n=1}^{\\infty} [\\frac{(-1)^{n + 1}}{n^{2}}] r^{n} \\text{ cos }(n\\theta)\\)",
      "\\(u (r, \\theta) = \\frac{\\pi}{2} + \\frac{2}{\\pi} \\sum_{n=1}^{\\infty} [\\frac{(-1)^{n} - 1}{n^{2}}] r^{n} \\text{ cos }(n\\theta)\\)",
      "\\(u (r, \\theta) = \\frac{\\pi}{2} - \\frac{2}{\\pi} \\sum_{n=1}^{\\infty} [\\frac{(-1)^{n} - 1}{n^{2}}] r^{n} \\text{ cos }(n\\theta)\\)",
    ],
    answer: "C",
  },
  {
    id: 45,
    marks: 1,
    type: "NAT",
    question: "The partial differential equation \\(7 \\frac{\\partial^2 u}{\\partial x^2} + 16 \\frac{\\partial^2 u}{\\partial x \\partial y} + 4 \\frac{\\partial^2 u}{\\partial y^2} = 0\\) is transformed to \\(A \\frac{\\partial^2 u}{\\partial {\\xi}^2} + B \\frac{\\partial^2 u}{\\partial {\\xi} \\partial {\\eta}} + C \\frac{\\partial^2 u}{\\partial {\\eta}^2} = 0\\) using \\(\\xi = y − 2x\\) and \\(\\eta = 7y − 2x\\) . Then, the value of \\(\\frac{1}{12^{3}} (B^{2} − 4 A C)\\) is _______.",
    answer: "12",
  },
  {
    id: 46,
    marks: 1,
    type: "NAT",
    question: "Let \\(u(x, t)\\) be the solution of \\(\\frac{\\partial^2 u}{\\partial t^2} = 0 , u(x,0) =f(x), \\frac{\\partial u}{\\partial t} (x,0) = 0, x \\epsilon R, t > 0.\\) where f is a twice continuously differentiable function. If \\(f(-2) = 4, f(0) = 0,\\) and \\(u(2, 2) = 8,\\) then the value of \\(u(1,3)\\) is _______________x",
    answer: "10 to 10",
  },
  {
    id: 47,
    marks: 2,
    type: "NAT",
    question: "If the Laplace equation \\(x \\frac{\\partial^{2} u}{\\partial x^{2}} + \\frac{\\partial^{2} u}{\\partial y^{2}} = 0\\) , 1 < x < 2, 1 < y < 2 with the boundary conditions \\(\\frac{\\partial u}{\\partial x} (1, y) = y, \\frac{\\partial u}{\\partial x} (2, y) = 5\\) , 1 < y < 2 and \\(\\frac{\\partial u}{\\partial y} (x, 1) = \\frac{\\alpha x^{2}}{7}, \\frac{\\partial u}{\\partial y} (x, 2) = x\\) , 1 < x < 2 has a solution, then the constant \\(\\alpha\\) is ________.",
    answer: "15",
  },
  {
    id: 48,
    marks: 2,
    type: "MSQ",
    question: "Let (R, \\(\\tau\\) ) be a topological space, where the topology \\(\\tau\\) is defined as \\(\\tau\\) = {U ⊆ R ∶ U = ∅ or 1 ∈ U}. Which of the following statements is/are correct?",
    options: [
      "(R, \\(\\tau\\) ) is first countable",
      "(R, \\(\\tau\\) ) is Hausdorff",
      "(R, \\(\\tau\\) ) is separable",
      "The closure of (1,5) is [1,5]",
    ],
    answer: [
      "A",
      "C",
    ],
  },
  {
    id: 49,
    marks: 2,
    type: "MSQ",
    question: "Let X = (R, T), where T is the smallest topology on R in which all the singleton sets are closed. Then, which of the following statements are TRUE?",
    options: [
      "[0, 1) is compact in X",
      "X is not first countable",
      "X is second countable",
      "X is first countable",
    ],
    answer: [
      "A",
      "B",
    ],
  },
  {
    id: 50,
    marks: 2,
    type: "MCQ",
    question: "Consider the ordered square \\(I_{0}^{2}\\) , the set [0,1] × [0,1] with the dictionary order topology. Let the general element of \\(I_{0}^{2}\\) be denoted by x × y, where x, y ∈ [0,1]. Then the closure of the subset S = { \\(x \\times \\frac{3}{4} : 0 < a < x < b < 1\\) } in \\(I_{0}^{2}\\) is",
    options: [
      "S U ((a,b] × {0}) U ([a,b) × {1})",
      "S U ([a,b) × {0}) U ((a,b] × {1})",
      "S U ((a,b) × {0}) U ((a,b) × {1})",
      "S U ((a,b] × {0})",
    ],
    answer: "A",
  },
  {
    id: 51,
    marks: 1,
    type: "MCQ",
    question: "Consider the topology \\(\\tau = \\big(U \\subseteq Z: Z \\backslash U \\text { is finite or } 0 \\in U \\big) \\text { on } Z.\\) Then, the topological space \\((Z.\\tau)\\) is ________",
    options: [
      ") compact but NOT connected (C) (B) (D)",
      "connected but NOT compact",
      "both compact and connected",
      "neither compact nor connected",
    ],
    answer: "A",
  },
  {
    id: 52,
    marks: 1,
    type: "MCQ",
    question: "Let \\(T_{1}\\) be the co-countable topology on R (the set of real numbers) and \\(T_{2}\\) be the co-finite topology on R. Consider the following statements: I. In (R, \\(T_{1}\\) ), the sequence { \\(\\frac{1}{n}\\) } \\(_{n = 1} ^{\\infty}\\) converges to 0. II. In (R, \\(T_{2}\\) ), the sequence { \\(\\frac{1}{n}\\) } \\(_{n = 1} ^{\\infty}\\) converges to 0. III. In (R, \\(T_{1}\\) ), there is no sequence of rational numbers which converges to √3. IV. In (R, \\(T_{2}\\) ), there is no sequence of rational numbers which converges to √3. Which of the above statements are TRUE?",
    options: [
      "I and II only",
      "II and III only",
      "III and IV only",
      "I and IV only",
    ],
    answer: "B",
  },
  {
    id: 53,
    marks: 1,
    type: "MCQ",
    question: "Let X and Y be two topological spaces. A continuous map f ∶ X → Y is said to be proper if f \\(^{-1}\\) (K) is compact in X for every compact subset K of Y, where f \\(^{-1}\\) (K) is defined by f \\(^{-1}\\) (K) = {x ∈ X ∶ f(x) ∈ K}. Consider R with the usual topology. If R ∖ {0} has the subspace topology induced from R and R × R has the product topology, then which of the following maps is proper?",
    options: [
      "f: R ∖ {0} → R defined by f(x) = x",
      "f: R × R → R × R defined by f(x, y) = (x + y, y)",
      "f: R × R → R defined by f(x, y) = x",
      "f: R × R → R defined by f(x, y) = x \\(^{2}\\) − y \\(^{2}\\)",
    ],
    answer: "B",
  },
  {
    id: 54,
    marks: 1,
    type: "MCQ",
    question: "Let p : ([0, 1], \\(T_{1}\\) ) → ({0, 1}, \\(T_{2}\\) ) be the quotient map, arising from the characteristic function on \\([\\frac{1}{2}, 1]\\) , where \\(T_{1}\\) is the subspace topology induced by the Euclidean topology on R. Which of the following statements is TRUE?",
    options: [
      "p is an open map but not a closed map",
      "p is a closed map but not an open map",
      "p is a closed map as well as an open map",
      "p is neither an open map nor a closed map",
    ],
    answer: "D",
  },
  {
    id: 55,
    marks: 2,
    type: "NAT",
    question: "Consider the following cost matrix of assigning four jobs to four persons: Then the minimum cost of the assignment problem subject to the constraint that job \\(\\text{J}_{4}\\) is assigned to person \\(\\text{P}_{2}\\) , is ________.",
    answer: "27",
  },
  {
    id: 56,
    marks: 2,
    type: "MCQ",
    question: "Let \\(\\alpha , \\beta \\in R, \\alpha \\neq 0.\\) The system \\(x_1 - 2x_2 + \\alpha x_3 = 8\\) \\(x_1 -x_2+ x_4= \\beta\\) \\(x_1,x_2,x_3,x_4 \\geq 0\\) has NO basic feasible solution if",
    options: [
      "\\(\\alpha <0, \\beta > 8\\)",
      "\\(\\alpha > 0, 0 < \\beta < 8\\)",
      "\\(\\alpha > 0, \\beta < 0\\)",
      "\\(\\alpha < 0, \\beta < 8\\)",
    ],
    answer: "D",
  },
  {
    id: 57,
    marks: 1,
    type: "MCQ",
    question: "Consider the linear programming problem (LPP): Maximize \\(4x_1 +6x_2\\) Subject to \\(x_1+x_2 \\leq 8,\\) \\(2x_1+3x_2 \\geq 18,\\) \\(x_1 \\geq 6, x_2,\\) is unrestricted in sign. Then the LPP has",
    options: [
      "no optimal solution",
      "only one basic feasible solution and that is optimal",
      "more than one basic feasible solution and a unique optimal solution",
      "infinitely many optimal solutions",
    ],
    answer: "B",
  },
  {
    id: 58,
    marks: 2,
    type: "NAT",
    question: "Let \\(X_{1}, X_{2}, X_{3}, X_{4}\\) be independent exponential random variables with mean 1, 1/2, 1/3, 1/4, respectively. Then Y = min ( \\(X_{1}, X_{2}, X_{3}, X_{4}\\) ) has exponential distribution with mean equal to _________.",
    answer: "0.1",
  },
  {
    id: 59,
    marks: 2,
    type: "NAT",
    question: "Suppose that 𝑋 is a population random variable with probability density function \\(f(x;\\theta) = \\begin{bmatrix}\\theta X^{\\theta-1} &\\text { if } 0 < x < 1 \\\\ 0, & \\text { Otherwise } , \\end{bmatrix}\\) where \\(\\theta\\) is a parameter. In order to test the null hypothesis \\(𝐻_0:\\theta =2,\\) against the alternative hypothesis \\(𝐻_1:\\theta =3,\\) the following test is used: Reject the null hypothesis if \\(𝑋_1 \\geq \\frac{1}{2}\\) and accept otherwise, where \\(X_1\\) is a random sample of size 1 drawn from the above population. Then the power of the test is _____",
    answer: "0,86 to 0.88",
  },
  {
    id: 60,
    marks: 1,
    type: "NAT",
    question: "Let \\(X \\sim B (5,\\frac{1}{2})\\) and \\(Y \\sim U (0,1)\\) . Then \\(\\frac{P( X + Y \\leq 2)}{P( X + Y \\geq 5)}\\) is equal to _______.",
    answer: "6",
  },
  {
    id: 61,
    marks: 1,
    type: "MCQ",
    question: "Let \\(F(x)\\) be the distribution function of a random variable \\(X.\\) Consider the functions \\(G_1(x) = \\big(F(x)\\big)^3. x \\in R\\) \\(G_2(x) = 1 - \\big(1- F(x)\\big)^5 , x \\in R.\\) Which of the above functions are distribution functions?",
    options: [
      "Neither \\(G_1 \\text { nor } G_2\\)",
      "Only \\(G_1\\)",
      "Only \\(G_2\\)",
      "Both \\(G_1 \\text { and } G_2\\)",
    ],
    answer: "D",
  },
  {
    id: 62,
    marks: 2,
    type: "NAT",
    question: "The value of \\(\\displaystyle\\lim_{n \\rightarrow \\infty} \\displaystyle\\int_0^1 nx^n e{^x}^{2} dx\\) is ___________(rounded off to three decimal places).",
    answer: "2.710 to 2.725",
  },
  {
    id: 63,
    marks: 2,
    type: "MCQ",
    question: "Consider the sequence { \\(g_{n}\\) } \\(_{n=1}^{\\infty}\\) of functions, where \\(g_{n}(x) = \\frac{x}{1 + n x^{2}}, x \\in \\text{R, } n \\in \\text{N and } g_{n}'(x)\\) is the derivative of \\(g_{n}(x)\\) with respect to x. (R is the set of all real numbers, N is the set of all natural numbers). Then which one of the following statements is TRUE?",
    options: [
      "{ \\(g_{n}\\) } \\(_{n=1}^{\\infty}\\) does NOT converge uniformly on R",
      "{ \\(g_{n}'\\) } \\(_{n=1}^{\\infty}\\) converges uniformly on any closed interval which does NOT contain 1",
      "{ \\(g_{n}'\\) } \\(_{n=1}^{\\infty}\\) converges point-wise to a continuous function on R",
      "{ \\(g_{n}'\\) } \\(_{n=1}^{\\infty}\\) converges uniformly on any closed interval which does NOT contain 0",
    ],
    answer: "D",
  },
  {
    id: 64,
    marks: 1,
    type: "MCQ",
    question: "Let \\(f: \\big(\\frac{-\\pi}{2}, \\frac{\\pi}{2} \\big) \\rightarrow\\) : be given by \\(f(x)= \\frac{\\pi}{2} +x-\\text { tan }^{-1} x.\\) Consider the following statements: \\(P: |f(x)-f(y)| < |x-y| \\text { for all } x.y \\epsilon \\big(\\frac{-\\pi}{2}, \\frac{\\pi}{2} \\big)\\) \\(Q: f\\) has a fixed point. Then",
    options: [
      "both P and Q are TRUE.",
      "Pis TRUE and Q is FALSE.",
      "P FALSE and Q 15 TRUE.",
      "both P and Q are FALSE.",
    ],
    answer: "D",
  },
  {
    id: 65,
    marks: 1,
    type: "MCQ",
    question: "Let C[0, 1] = {f ∶ [0, 1] → R ∶ f is continuous}. Consider the metric space (C[0,1], \\(\\text{d}_{\\infty}\\) ), where \\(\\text{d}_{\\infty}\\) (f, g) = sup{|f(x) − g(x)| ∶ x ∈ [0, 1]} for f, g ∈ C[0,1]. Let \\(\\text{f}_{\\circ}(x) = 0\\) for all x ∈ [0,1] and X = {f ∈ (C[0, 1], \\(\\text{d}_{\\infty}\\) ) ∶ \\(\\text{d}_{\\infty}\\) ( \\(\\text{f}_{\\circ}, \\text{f} \\geq \\frac{1}{2}\\) }. Let \\(\\text{f}_{1}, \\text{f}_{2}\\) ∈ C[0, 1] be defined by \\(\\text{f}_{1}(x) = x\\) and \\(\\text{f}_{2}(x) = 1 - x\\) for all x ∈ [0,1]. Consider the following statements: P: \\(\\text{f}_{1}\\) is in the interior of X. Q: \\(\\text{f}_{2}\\) is in the interior of X. Which of the following statements is correct?",
    options: [
      "P is TRUE and Q is FALSE",
      "P is FALSE and Q is TRUE",
      "Both P and Q are FALSE",
      "Both P and Q are TRUE",
    ],
    answer: "D",
  },
];

export default test04Questions;