import type { TestQuestion } from "../testTypes";

// Test 06 generated directly from the uploaded NPTEL HTML (source id=252).
// Source-provided Expected answers are preserved. Image-only content is represented by a placeholder because the HTML upload does not include the referenced image assets.

const test06Questions: TestQuestion[] = [
  {
    id: 1,
    marks: 2,
    type: "MCQ",
    question: "Two trains started at 7AM from the same point. The first train travelled north at a speed of 80km/h and the second train travelled south at a speed of 100 km/h. The time at which they were 540 km apart is _______ AM.",
    options: ["9", "10", "11", "11.30"],
    answer: "B",
  },
  {
    id: 2,
    marks: 2,
    type: "MCQ",
    question: "Forty students watched films A, B and C over a week. Each student watched either only one film or all three. Thirteen students watched film A, sixteen students watched film B and nineteen students watched film C. How many students watched all three films?",
    options: ["0", "2", "4", "8"],
    answer: "C",
  },
  {
    id: 3,
    marks: 1,
    type: "MCQ",
    question: "The figure below shows the front and rear view of a disc, which is shaded with identical patterns. The disc is flipped once with respect to any one of the fixed axes 1-1, 2-2 or 3-3 chosen uniformly at random.\n\nWhat is the probability that the disc DOES NOT retain the same front and rear views after the flipping operation?\n\n[Image from NPTEL source]",
    options: ["0", "\\(\\frac{1}{3}\\)", "\\(\\frac{2}{3}\\)", "1"],
    answer: "C",
  },
  {
    id: 4,
    marks: 1,
    type: "MCQ",
    question: "The perimeters of a circle, a square and an equilateral triangle are equal. Which one of the following statements is true?",
    options: ["The circle has the largest area.", "The square has the largest area.", "The equilateral triangle has the largest area.", "All the three shapes have the same area."],
    answer: "A",
  },
  {
    id: 5,
    marks: 2,
    type: "MCQ",
    question: "\"If you are looking for a history of India, or for an account of the rise and fall of the British Raj, or for the reason of the cleaving of the subcontinent into two mutually antagonistic parts and the effects this mutilation will have in the respective sections, and ultimately on Asia, you will not find it in these pages, for though I have spent a lifetime in the country. I lived too near the seat of events, and was too intimately associated with the actors, to get the perspective needed for the impartial recording of these matters.\"\n\nWhich of the following statements best reflects the author's opinion?",
    options: ["An intimate association does not allow for the necessary perspective.", "Matters are recorded with an impartial perspective.", "An intimate association offers an impartial perspective.", "Actors are typically associated with the impartial recording of matters."],
    answer: "A",
  },
  {
    id: 6,
    marks: 1,
    type: "MCQ",
    question: "As you grow older, an injury to your _________ may take longer to _________.",
    options: ["heel / heel", "heal / heel", "heal / heal", "heel / heal"],
    answer: "D",
  },
  {
    id: 7,
    marks: 2,
    type: "MCQ",
    question: "Each of P. Q. R. S. W. X. Y and Z has been married at most once. X and Y are married and have two children P and Q. Z is the grandfather of the daughter S of P. Further. Z and W are married and are parents of R. Which one of the following must necessarily be FALSE?",
    options: ["X is the mother-in-law of R", "P is a son of X and Y", "Pand Rare not married to each other", "Q cannot be married to R"],
    answer: "D",
  },
  {
    id: 8,
    marks: 2,
    type: "MCQ",
    question: "Since the last one year, after a 125 basis point reduction in repo rate by the Reserve Bank of India, banking institutions have been making a demand to reduce interest rates on small saving schemes. Finally, the government announced yesterday a reduction in interest rates on small saving schemes to bring them on par with fixed deposit interest rates.\n\nWhich one of the following statements can be inferred from the given passage?",
    options: ["Whenever the Reserve Bank of India reduces the repo rate, the interest rates on small saving schemes are also reduced", "Interest rates on small saving schemes are always maintained on par with fixed deposit interest rates", "The government sometimes takes into consideration the demands of banking institutions before reducing the interest rates on small saving schemes", "A reduction in interest rates on small saving schemes follow only after a reduction in repo rate by the Reserve Bank of India"],
    answer: "C",
  },
  {
    id: 9,
    marks: 1,
    type: "MCQ",
    question: "The value of the expression \\(\\frac{1}{1 + log_{u} vw} + \\frac{1}{1 + log_{v} wu} + \\frac{1}{1 + log_{w} uv}\\) is ________.",
    options: ["-1", "0", "1", "3"],
    answer: "C",
  },
  {
    id: 10,
    marks: 1,
    type: "MCQ",
    question: "[Image from NPTEL source]",
    options: ["", "", "", ""],
    answer: "A",
  },
  {
    id: 11,
    marks: 2,
    type: "NAT",
    question: "Let \\( \\vec{F} = (x + 2y)e^z\\hat{î} + (ye^2 + x^2) \\hat {j} + y^2z \\hat{k} \\) and let S be the surface \\( x^2+y^2+z=1, z \\geq 0.\\) If it is a unit normal to S and\n\n\\(\\mid\\int\\int{_s}(\\nabla \\times \\vec{F}).\\hat{n}dS\\mid = \\alpha \\pi \\)\n\nThen \\( \\alpha \\) is equal to ___________",
    answer: { min: 2, max: 2 },
  },
  {
    id: 12,
    marks: 2,
    type: "NAT",
    question: "Let D = {\\((x, y) \\in \\text{ R}^{2} : 1 \\leq x \\leq 1000, 1 \\leq y \\leq 1000\\)}. Define\n\n\\(f(x,y) = \\frac{xy}{2} + \\frac{500}{x} + \\frac{500}{y}\\).\n\nThen the minimum value of f on D is equal to ________.",
    answer: 150,
  },
  {
    id: 13,
    marks: 2,
    type: "MCQ",
    question: "Let V be the solid region in \\( R^3 \\) bounded by the paraboloid \\( y = (x^2 + z^2) \\) and the plane \\( y = 4.\\) Then the value of \\( \\int\\int \\int_V 15 \\sqrt { x^2 + z^2} dV \\) is",
    options: ["\\(128 \\pi\\)", "\\(64 \\pi\\)", "\\(28 \\pi\\)", "\\(256 \\pi\\)"],
    answer: "A",
  },
  {
    id: 14,
    marks: 2,
    type: "NAT",
    question: "Let R be the region in the xy-plane bounded by the curves \\(y = x^{2}, y = 4 x^{2}, x y = 1 \\text{ and } x y = 5\\).\n\nThen the value of the integral \\(\\int \\int_R \\frac{y^{2}}{x} dy dx\\) is equal to ________.",
    answer: 12,
  },
  {
    id: 15,
    marks: 1,
    type: "NAT",
    question: "Let \\( f : R^2 \\rightarrow R \\) be differentiable. Let \\( D_uf(0, 0) \\text { and } D_vf (0,0) \\) be the directional derivatives of f at \\( (0,0) \\) in the directions of the unit vectors \\( u= \\big(\\frac{1}{\\sqrt 5},\\frac{2}{\\sqrt 5}\\big) \\text { and } v\\big(\\frac{1}{\\sqrt 2},\\frac{-1}{\\sqrt 2}\\big), \\) respectively. If \\( D_uf (0,0) = \\sqrt 5 \\text { and } D_v,f(0,0) = \\sqrt 2,\\text { then } \\frac{\\partial f}{\\partial x}(0,0)+ \\frac{\\partial f}{\\partial y} (0,0) = \\)",
    answer: { min: 4, max: 4 },
  },
  {
    id: 16,
    marks: 1,
    type: "MCQ",
    question: "Let f : R\\(^{2} \\rightarrow\\) R be defined by\n\n\\(f (x, y) = x^{6} - 2 x^{2} y - x^{4} y + 2 y^{2}\\).\n\n(R is the set of all real numbers and R\\(^{2}\\) = { \\((x, y) : x, y \\in\\) R } )\n\nWhich one of the following statements is TRUE?",
    options: ["f has a local maximum at origin", "f has a local minimum at origin", "f has a saddle point at origin", "The origin is not a critical point of f"],
    answer: "C",
  },
  {
    id: 17,
    marks: 1,
    type: "NAT",
    question: "Let S be the portion of the plane z = 2x + 2y − 100 which lies inside the cylinder \\(x^{2} + y^{2} = 1\\). If the surface area of S is \\(\\alpha \\pi\\), then the value of α is equal to ___________.",
    answer: 3,
  },
  {
    id: 18,
    marks: 2,
    type: "NAT",
    question: "Let y be the triangular path connecting the points \\( (0,0), (2,2) \\text { and } (0,2) \\) in the counter- clockwise direction in \\( R^2.\\) Then\n\n\\( I = \\displaystyle\\oint_\\gamma \\text { sin } (x^3) dx+ 6xy dy \\) is equal to _______________",
    answer: "5.4 :  5.6",
  },
  {
    id: 19,
    marks: 2,
    type: "NAT",
    question: "Let A = [\\(a_{ij}\\)] be a 3 × 3 real matrix such that\n\n\\(A \\begin{bmatrix}1 \\\\ 2 \\\\ 1 \\end{bmatrix} = 2 \\begin{bmatrix}1 \\\\ 2 \\\\ 1 \\end{bmatrix}, A \\begin{bmatrix}0 \\\\ 1 \\\\ 1 \\end{bmatrix} = 2 \\begin{bmatrix}0 \\\\ 1 \\\\ 1 \\end{bmatrix} \\text{ and } A \\begin{bmatrix}-1 \\\\ 1 \\\\ 0 \\end{bmatrix} = 4 \\begin{bmatrix}-1 \\\\ 1 \\\\ 0 \\end{bmatrix}\\).\n\nIf m is the degree of the minimal polynomial of A, then \\(a_{11} + a_{21} + a_{31} + m\\) equals __________.",
    answer: 4,
  },
  {
    id: 20,
    marks: 2,
    type: "NAT",
    question: "Let \\( V \\big\\{p : p(x)= a_0 + a_1x + a_2x^2, a_0, a_1, a_2 \\in R\\big\\} \\) be the vector space of all polynomials of degree at most 2 over the real field \\( R. \\text { Let } T:V \\rightarrow V \\) be the linear operator given by\n\n\\( T(p) = (p(0)- p(1))+(p(0) + p(1)) x + p(0) x^2.\\)\nThen the sum of the eigenvalues of T is ___________.",
    answer: { min: 1, max: 1 },
  },
  {
    id: 21,
    marks: 1,
    type: "MCQ",
    question: "Let \\( V \\) denote the vector space \\( C^5[a,b] \\text { over } R \\text { and } W = \\big\\{f \\in V : \\frac{d^4f}{dt^4}+ 2 \\frac{d^2f}{dt^2} -f =0\\big\\} \\). Then",
    options: ["\\(\\text { dim } (V) = \\infty \\text { and dim } (W) = \\infty\\)", "\\(\\text { dim } (V) = \\infty \\text { and dim } (W) = 4\\)", "\\(\\text { dim } (V) = 6\\text { and dim } (W) = 5\\)", "\\(\\text { dim } (V) = 5 \\text { and dim } (W) = 4\\)"],
    answer: "B",
  },
  {
    id: 22,
    marks: 1,
    type: "MCQ",
    question: "Let M = \\(\\begin{bmatrix}4 & -3 \\\\1 & 0 \\end{bmatrix}\\)\n\nConsider the following statements:\n\nP: \\(\\text{M}^{8} + \\text{M}^{12}\\) is diagonalizable.\n\nQ: \\(\\text{M}^{7} + \\text{M}^{19}\\) is diagonalizable.\n\nWhich of the following statements is correct?",
    options: ["P is TRUE and Q is FALSE", "P is FALSE and Q is TRUE", "Both P and Q are FALSE", "Both P and Q are TRUE"],
    answer: "D",
  },
  {
    id: 23,
    marks: 2,
    type: "NAT",
    question: "If \\( \\alpha \\in C \\text { with } |a|<,\\) then the value of\n\n\\( \\frac{(1-|a|^2)}{\\pi} \\displaystyle\\int_\\Gamma \\frac{|dz|}{|z+a|^2}, \\)\nwhere \\( \\Gamma \\) is the simple closed curve |𝑧|=1 taken with the positive orientation, is _________",
    answer: "1.99 t0 2.01",
  },
  {
    id: 24,
    marks: 2,
    type: "NAT",
    question: "Let C be the simple, positively oriented circle of radius 2 centered at the origin in the complex plane. Then\n\n\\( \\frac{1}{\\pi i }\\displaystyle\\int_C \\big(ze^{(1\\backslash z) + \\text { tan }\\big(\\frac{z}{2}\\big) + \\frac{1}{(z-1)(z-3)^3}}\\big) dz \\) equals __________.",
    answer: { min: 3, max: 3 },
  },
  {
    id: 25,
    marks: 1,
    type: "NAT",
    question: "The radius of convergence of the series\n\n\\(\\sum_{n≥0} 3^{n+1} z^{2n}, z \\in \\text{C}\\)\n\nis __________(round off to TWO decimal places).",
    answer: "0.55 – 0.59",
  },
  {
    id: 26,
    marks: 1,
    type: "MCQ",
    question: "Let \\( f(z) = (x^2 + y^2)+i2xy \\text { and } g(z) = 2xy+i(y^2-x^2) \\text { for } Z = x+iy \\in C. \\) Then, in the complex plane \\( C.\\)",
    options: ["\\(f\\) is analytic and \\(g\\) is NOT analytic.", "\\(f\\) is NOT analytic and \\(g\\) is analytic", "neither \\(f \\text { nor } g\\) is analytic.", "both \\(f \\text { and }  g\\) are analytic."],
    answer: "B",
  },
  {
    id: 27,
    marks: 2,
    type: "NAT",
    question: "Consider the initial value problem\n\nx\\(^{2}\\) y\" - 6 y = 0, y(1) = \\(\\alpha\\), y'(1) = 6.\n\nIf y(x) → 0 as x → 0\\(^{+}\\), then \\(\\alpha\\) is equal to ________.",
    answer: 2,
  },
  {
    id: 28,
    marks: 2,
    type: "MCQ",
    question: "The critical point of the differential equation\n\n\\(\\frac{d^2y}{dt^2} + 2 \\alpha \\frac{dy}{dt} + \\beta^2 y =0 ,\\alpha >\\beta >0,\\)\nis a",
    options: ["node and is asymptotically stable.", "spiral pont and is asymptotically stable.", "node and is unstable.", "saddle point and is unstable"],
    answer: "A",
  },
  {
    id: 29,
    marks: 2,
    type: "NAT",
    question: "Consider the ordinary differential equation (ODE)\n\n4(ln x) y′′ + 3 y′ + y = 0, x > 1.\n\nIf \\(r_{1}\\) and \\(r_{2}\\) are the roots of the indicial equation of the above ODE at the regular singular point x = 1, then \\(|r_{1} - r_{2}|\\) is equal to _________ (rounded off to 2 decimal places).",
    answer: "0.24 – 0.26",
  },
  {
    id: 30,
    marks: 1,
    type: "NAT",
    question: "Let y(t) be the solution of the initial value problem\n\ny′′ + 4y = \\(\\begin{cases}2, & 2 < t < \\infty,\\\\t, & 0 ≤ t ≤ 2,\\end{cases}\\) and y(0) = y′(0) = 0.\n\nIf α = y (\\(\\frac{\\pi}{2}\\)), then the value of \\(\\frac{4}{\\pi}\\alpha\\) is ________(rounded off to 2 decimal places).",
    answer: "0.49 – 0.51",
  },
  {
    id: 31,
    marks: 1,
    type: "MCQ",
    question: "The solution to the integral equation \\( \\varphi (x) = x + \\displaystyle\\int_0^x \\text { sin } (x- \\xi )\\varphi ( \\xi )d \\xi \\) is_________",
    options: ["\\(x^2 + \\frac{x^3}{3}\\)", "\\(x - \\frac{x^3}{3!}\\)", "\\(x + \\frac{x^3}{3!}\\)", "\\(x^2 - \\frac{x^3}{3!}\\)"],
    answer: "C",
  },
  {
    id: 32,
    marks: 2,
    type: "NAT",
    question: "Suppose that \\( \\phi_1 \\text { and } \\phi_2 \\) are linearly independent solutions of the differential equation\n\n\\( 2x^2y''-(x+x^2)y' + (x^2-2)y = 0,\\)\n\nand \\(\\phi_1 (0) = 0.\\) Then the smallest positive integer n such that\n\n\\( \\displaystyle\\lim_{x \\rightarrow 0} x^n \\frac{\\phi_2(x)}{\\phi_1(x)} =0 \\) is ________",
    answer: { min: 3, max: 3 },
  },
  {
    id: 33,
    marks: 2,
    type: "NAT",
    question: "Let G be a group of order \\( 5^4\\) with center having \\( 5^2\\) elements. Then the number of conjugacy classes in G is ___________",
    answer: { min: 145, max: 145 },
  },
  {
    id: 34,
    marks: 1,
    type: "NAT",
    question: "Let F be a field with \\(7^{6}\\) elements and let K be a subfield of F with 49 elements. Then the dimension of F as a vector space over K is _________.",
    answer: 3,
  },
  {
    id: 35,
    marks: 2,
    type: "NAT",
    question: "Let \\( K = Q (\\sqrt{3+2\\sqrt{2}}, \\omega), \\)\n\nwhere \\( \\omega\\) is primitive cube root of unity. Then the degree of extensionof \\( K \\text { over } Q \\) is ______________",
    answer: { min: 4, max: 4 },
  },
  {
    id: 36,
    marks: 2,
    type: "MCQ",
    question: "Let \\(a > 0\\). Define \\(D_{a} : L^{2}\\)(R) → \\(L^{2}\\)(R) by \\((D_{a} f) (x) = \\frac{1}{\\sqrt{2}} f (\\frac{x}{a})\\), almost every-where, for \\(f \\in L^{2}\\)(R). Then, which of the following statements are TRUE?",
    options: ["\\(D_{a}\\) is a linear isometry", "\\(D_{a}\\) is a bijection", "\\(D_{a} \\circ D_{b} = D_{a + b}, b > 0\\)", "\\(D_{a}\\) is bounded from below"],
    answer: ["A", "B", "D"],
  },
  {
    id: 37,
    marks: 2,
    type: "MCQ",
    question: "Let {\\(\\phi_{0}, \\phi_{1}, \\phi_{2}, ...\\)} be an orthonormal set in \\(L^{2}\\)[−1, 1] such that \\(\\phi_{n} = C_{n} P_{n}\\), where \\(C_{n}\\) is a constant and \\(P_{n}\\) is the Legendre polynomial of degree n, for each n ∈ N ∪ {0}.\n\nThen, which of the following statements are TRUE?",
    options: ["\\(\\phi_{6}(1) = 1\\)", "\\(\\phi_{7}(-1) = 1\\)", "\\(\\phi_{7}(-1) = \\sqrt{\\frac{15}{2}}\\)", "\\(\\phi_{6}(-1) = \\sqrt{\\frac{13}{2}}\\)"],
    answer: ["C", "D"],
  },
  {
    id: 38,
    marks: 1,
    type: "MCQ",
    question: "Let V = C\\(^{1}\\) [0, 1], X = (C[0, 1], || ||\\(_{\\infty}\\)) and Y = (C[0, 1], || ||\\(_{2}\\)). Then V is",
    options: ["dense in X but NOT in Y", "dense in Y but NOT in X", "dense in both X and Y", "neither dense in X nor dense in Y"],
    answer: "C",
  },
  {
    id: 39,
    marks: 2,
    type: "NAT",
    question: "Let the following discrete data be obtained from a curve \\( 𝑦=𝑦(𝑥):\\)\n\nLet the following discrete data be obtained from a curve 𝑦=𝑦(𝑥):\n\nx : 0 0.25 0.5 0.75 1.0\n\ny: 1 0.9896 0.9589 0.9089 0.8415\n\nLet 𝑆 be the solid of revolution obtained by rotating the above curve about the \\( 𝑥-\\text { axis } between 0 x = \\text { and } 𝑥=1 \\text { and let } 𝑉 \\) denote its volume. The approximate value of \\( 𝑉 \\) , obtained using Simpson’s \\( \\frac{1}{3} \\) rule, is ______________",
    answer: { min: 2.81, max: 2.83 },
  },
  {
    id: 40,
    marks: 1,
    type: "MCQ",
    question: "Consider the iterative scheme\n\n\\( x_n = \\frac {x_{n-1}}{2} + \\frac{3}{x_{n-1}}, n \\geq 1 , \\)\n\nwith initial point \\( x_0 > 0. \\)\n\nThen the sequence \\( [x_n] \\)",
    options: ["converges only if \\(x_0>1\\)", "converges only if \\(x_0  <3\\)", "converges for any \\(x_0\\)", "does not converge for any \\(x_0\\)"],
    answer: "C",
  },
  {
    id: 41,
    marks: 1,
    type: "NAT",
    question: "If the fourth order divided difference of \\( f(x)=\\alpha x^4+5x^3+3x+2, \\alpha \\in R.\\) at the points 0.1, 0.2, 0.3, 0.4, 0.5 is 5, then \\( \\alpha \\) equals _____",
    answer: { min: 5, max: 5 },
  },
  {
    id: 42,
    marks: 2,
    type: "MCQ",
    question: "Let \\( u (r,\\theta) \\) be the bounded solution of the following boundary value problem in polar coordinates:\n\n\\( r^2 \\frac{\\partial^2 u}{\\partial r^2} + r \\frac{\\partial u}{\\partial r} + \\frac{\\partial^2 u}{\\partial \\theta^2} = 0 < r < 2 \\text { and } 0 \\leq \\theta \\leq 2 \\pi \\)\n\n\\( u(2,\\theta) = \\text { cos }^2 \\theta , 0 \\leq \\theta 2 \\pi . \\)\n\nThen \\( u ( 1, \\pi / 2) + u (1, \\pi/4 ) \\) equals ____",
    options: ["1", "\\(\\frac{9}{8}\\)", "\\(\\frac{7}{8}\\)", "\\(\\frac{3}{8}\\)"],
    answer: "B",
  },
  {
    id: 43,
    marks: 2,
    type: "MCQ",
    question: "Consider the second-order partial differential equation (PDE)\n\n\\(\\frac{\\partial ^2 u}{\\partial^2 u } + 4 \\frac{\\partial ^ 2u}{\\partial x \\partial y } + ( x^2 + 4y^2) \\frac{\\partial^2 u}{\\partial y^2}= \\text { sin } (x+y). \\)\nConsider the following statements:\nP: The PDE is parabolic on the ellipse \\(\\frac{x^2}{4} +y^2= 1.\\)\n\nQ: The PDF. is hyperbolic inside the ellipse \\(\\frac{x^2}{4}+y^2 = 1. \\) Then",
    options: ["both P and Q are TRUE.", "P is TRUE and Q 15 FALSE.", "Pis FALSE and Q is TRUE.", "both P and Q are FALSE."],
    answer: "A",
  },
  {
    id: 44,
    marks: 2,
    type: "NAT",
    question: "Let u(x, t), x ∈ R, t ≥ 0, be the solution of the initial value problem\n\n\\(u_{tt} = u_{xx}\\)\n\\(u(x, 0) = x\\)\n\\(u_{t}(x, 0) = 1\\).\n\nThen u(2,2) is equal to _______.",
    answer: 4,
  },
  {
    id: 45,
    marks: 1,
    type: "NAT",
    question: "Let \\( u(x, t) \\) be the solution of\n\n\\( \\frac{\\partial^2 u}{\\partial t^2} = 0 , u(x,0) =f(x), \\frac{\\partial u}{\\partial t} (x,0) = 0, x \\epsilon R, t > 0. \\) where f is a twice continuously differentiable function. If \\( f(-2) = 4, f(0) = 0, \\) and \\( u(2, 2) = 8, \\) then the value of \\( u(1,3) \\) is _______________x",
    answer: { min: 10, max: 10 },
  },
  {
    id: 46,
    marks: 1,
    type: "MCQ",
    question: "The partial differential equation\n\n\\((x^{2} + y^{2} - 1) \\frac{\\partial^2 u}{\\partial x^2} + 2 \\frac{\\partial^2 u}{\\partial x \\partial y} + (x^{2} + y^{2} - 1) \\frac{\\partial^2 u}{\\partial y^2} = 0\\)\n\nis",
    options: ["parabolic in the region \\(x^{2} + y^{2} > 2\\)", "hyperbolic in the region \\(x^{2} + y^{2} > 2\\)", "elliptic in the region \\(0 < x^{2} + y^{2} < 2\\)", "hyperbolic in the region \\(0 < x^{2} + y^{2} < 2\\)"],
    answer: "D",
  },
  {
    id: 47,
    marks: 1,
    type: "NAT",
    question: "Let \\( u(x, t)\\) be the d'Alembert's solution of the initial value problem for the wave equation\n\n\\( U_{tt}- c^2 U_{xx} = 0 \\)\n\n\\( u(x, 0) = f(x), u_t(x, 0) = g(x),\\)\n\nwhere \\( c \\) is a positive real number and \\( f, g \\) are smooth odd functions. Then, \\( u(0,1) \\) is equal to _______",
    answer: { min: -0.1, max: 0.1 },
  },
  {
    id: 48,
    marks: 2,
    type: "MCQ",
    question: "Consider the following topologies on the set \\( R \\) of all real numbers.\n\n\\( T_1 \\) is the upper limit topology having all sets \\( (a, b) \\) as basis.\n\n\\( T_2=\\big\\{U \\subset R :R \\backslash U \\text { is finite }\\big\\} \\cup \\big\\{ \\phi\\big\\} \\)\n\n\\( T_3\\) is the standard topology having all sets \\( (a, b) \\) as basis. Then",
    options: ["\\(T_2 \\subset T_3 \\subset T_1\\)", "\\(T_1 \\subset T_2 \\subset T_3\\)", "\\(T_3 \\subset T_2 \\subset T_1\\)", "\\(T_2 \\subset T_1 \\subset T_3\\)"],
    answer: "A",
  },
  {
    id: 49,
    marks: 2,
    type: "MCQ",
    question: "Let X = (R, T), where T is the smallest topology on R in which all the singleton sets are closed. Then, which of the following statements are TRUE?",
    options: ["[0, 1) is compact in X", "X is not first countable", "X is second countable", "X is first countable"],
    answer: ["A", "B"],
  },
  {
    id: 50,
    marks: 2,
    type: "MCQ",
    question: "Consider the ordered square \\(I_{0}^{2}\\), the set [0,1] × [0,1] with the dictionary order topology. Let the general element of \\(I_{0}^{2}\\) be denoted by x × y, where x, y ∈ [0,1]. Then the closure of the subset\n\nS = { \\(x \\times \\frac{3}{4} : 0 < a < x < b < 1\\) } in \\(I_{0}^{2}\\)\n\nis",
    options: ["S U ((a,b] × {0}) U ([a,b) × {1})", "S U ([a,b) × {0}) U ((a,b] × {1})", "S U ((a,b) × {0}) U ((a,b) × {1})", "S U ((a,b] × {0})"],
    answer: "A",
  },
  {
    id: 51,
    marks: 1,
    type: "MCQ",
    question: "Let X be a connected topological space such that there exists a non-constant continuous function f: X \\(\\rightarrow\\) R, where R is equipped with the usual topology. Let f(X) = {f(x) : x ∈ X}. Then",
    options: ["X is countable but f(X) is uncountable", "f(X) is countable but X is uncountable", "both f(X) and X are countable", "both f(X) and X are uncountable"],
    answer: "D",
  },
  {
    id: 52,
    marks: 1,
    type: "MCQ",
    question: "Let \\( X \\text{ and } Y \\)be topological spaces and let \\( f: XY \\) be a continuous surjective function. Which one of the following statements is TRUE?",
    options: ["If \\(X\\) is separable, then \\(Y\\) is separable.", "If \\(X\\) is first countable, then \\(Y\\) is first countable.", "If \\(X\\) is Hausdorff, then Y is Hausdorff.", "If \\(X\\) is regular, then \\(Y\\) is regular"],
    answer: "A",
  },
  {
    id: 53,
    marks: 1,
    type: "MCQ",
    question: "Let \\(T_{1}\\) be the co-countable topology on R (the set of real numbers) and \\(T_{2}\\) be the co-finite topology on R.\n\nConsider the following statements:\n\nI. In (R,\\(T_{1}\\)), the sequence {\\(\\frac{1}{n}\\)} \\(_{n = 1} ^{\\infty}\\) converges to 0.\n\nII. In (R, \\(T_{2}\\)), the sequence {\\(\\frac{1}{n}\\)} \\(_{n = 1} ^{\\infty}\\) converges to 0.\n\nIII. In (R,\\(T_{1}\\)), there is no sequence of rational numbers which converges to √3.\n\nIV. In (R, \\(T_{2}\\)), there is no sequence of rational numbers which converges to √3.\n\nWhich of the above statements are TRUE?",
    options: ["I and II only", "II and III only", "III and IV only", "I and IV only"],
    answer: "B",
  },
  {
    id: 54,
    marks: 1,
    type: "MCQ",
    question: "Let p : ([0, 1], \\(T_{1}\\)) → ({0, 1}, \\(T_{2}\\)) be the quotient map, arising from the characteristic function on \\([\\frac{1}{2}, 1]\\), where \\(T_{1}\\) is the subspace topology induced by the Euclidean topology on R. Which of the following statements is TRUE?",
    options: ["p is an open map but not a closed map", "p is a closed map but not an open map", "p is a closed map as well as an open map", "p is neither an open map nor a closed map"],
    answer: "D",
  },
  {
    id: 55,
    marks: 2,
    type: "NAT",
    question: "Consider the Linear Programming Problem P:\n\nMaximize \\(3x_{1} + 2x_{2} + 5x_{3}\\)\n\nsubject to\n\n\\(x_{1} + 2x_{2} + x_{3} ≤ 44\\),\n\\(x_{1} + 2x_{3} ≤ 48\\),\n\\(x_{1} + 4x_{2} ≤ 52\\),\n\\(x_{1} ≥ 0, x_{2} ≥ 0, x_{3} ≥ 0\\).\n\nThe optimal value of the problem P is equal to ____________.",
    answer: 140,
  },
  {
    id: 56,
    marks: 2,
    type: "NAT",
    question: "Let \\( \\alpha \\epsilon R , \\text { If } (3,0,0 \\beta ) \\) is an optimal solution of the linear programming problem minimize \\( x_1 + x_2 +x_3 - \\alpha x_4 \\)\n\nsubject to\n\n\\( 2x_1 -x_2+x_3 =6 \\)\n\n\\( -x_1 + x_2+x_4 =3 \\)\n\n\\( x_1, x_2,x_3,x_4 \\leq 0 \\)\n\nthen the maximum value of \\( \\beta - \\alpha \\) is ___________",
    answer: { min: 7, max: 7 },
  },
  {
    id: 57,
    marks: 1,
    type: "NAT",
    question: "Consider the Linear Programming Problem P:\n\nMaximize \\( 2x_1 + 3x_2 \\)\n\nsubject to\n\n\\( 2x_1 +x_2 \\leq 6,\\)\n\n\\( -x_1+X_2 \\leq 1,\\)\n\n\\( x_1 + x_2 \\leq 3,\\)\n\n\\( x_1 \\geq 0 \\text { and } x_2 \\geq 0.\\)\nThen the optimal value of the dual of P is equal to _________.",
    answer: { min: 8, max: 8 },
  },
  {
    id: 58,
    marks: 2,
    type: "MCQ",
    question: "Suppose that \\( 𝑋_1,𝑋_2,…,𝑋_𝑛 \\) is a random sample of size \\( 𝑛 \\) drawn from a population with probability density function\n\n\\( f(x;\\theta)= \\begin{cases}\\frac{x}{\\theta^2} e^-\\frac{x}{\\theta} \\text { if } x > 0\\\\ 0 & \\text { otherwise } ,\\end{cases} \\)\n\nwhere \\( \\theta \\) is a parameter such that \\( \\theta > 0.\\) The maximum likelihood estimator of \\( \\theta \\) is",
    options: ["\\(\\frac{\\displaystyle\\sum_{i=1}^{n} X_i}{n}\\)", "\\(\\frac{\\displaystyle\\sum_{i=1}^{n} X_i}{n-1}\\)", "\\(\\frac{\\displaystyle\\sum_{i=1}^{n} X_i}{2n}\\)", "\\(\\frac{2\\displaystyle\\sum_{i=1}^{n} X_i}{n}\\)"],
    answer: "C",
  },
  {
    id: 59,
    marks: 2,
    type: "NAT",
    question: "Let \\(X_{1}, X_{2}, X_{3}, X_{4}\\) be independent exponential random variables with mean 1, 1/2, 1/3, 1/4, respectively. Then Y = min (\\(X_{1}, X_{2}, X_{3}, X_{4}\\)) has exponential distribution with mean equal to _________.",
    answer: 0.1,
  },
  {
    id: 60,
    marks: 1,
    type: "MCQ",
    question: "Let \\( X_1, X_2,.... X_n (n \\geq 2) \\) be independent and identically distributed random variables with finite variance \\( \\sigma^2 \\text { and let } \\bar{X}= \\frac{1}{n} \\displaystyle\\sum_{i=1}^n X_i. \\) Then the covariance between \\( \\bar{X} \\text { and } {X_1}-\\bar{X} \\) is",
    options: ["0", "\\(-\\sigma^2\\)", "\\(\\frac{-\\sigma^2}{n}\\)", "\\(\\frac{\\sigma^2}{n}\\)"],
    answer: "A",
  },
  {
    id: 61,
    marks: 1,
    type: "NAT",
    question: "Let \\(X \\sim B (5,\\frac{1}{2})\\) and \\(Y \\sim U (0,1)\\). Then \\(\\frac{P( X + Y \\leq 2)}{P( X + Y \\geq 5)}\\) is equal to _______.",
    answer: 6,
  },
  {
    id: 62,
    marks: 2,
    type: "MCQ",
    question: "Let\n\n\\(f_{n}(x) = \\frac{x^{2}}{x^{2} + (1 - nx)^{2}}, x \\in [0, 1], n = 1, 2, 3, ... .\\)\n\nThen, which of the following statements is TRUE?",
    options: ["{ \\(f_{n}\\) } is not equicontinuous on [0, 1]", "{ \\(f_{n}\\) } is uniformly convergent on [0, 1]", "{ \\(f_{n}\\) } is equicontinuous on [0, 1]", "{ \\(f_{n}\\) } is uniformly bounded and has a subsequence converging uniformly on [0, 1]"],
    answer: "A",
  },
  {
    id: 63,
    marks: 2,
    type: "MCQ",
    question: "Let \\( S_n =\\sum_{k=1}^n \\frac{1}{k} \\text { and } l_n = \\int_1^n \\frac{x-[-x]}{x^2} dx. \\)\n\nThen \\( S_{10} + I_{10} \\) is equal to",
    options: ["ln 10 + 1", "ln 10 -1", "ln 10 - \\(\\frac{1}{10}\\)", "ln 10 + \\(\\frac{1}{10}\\)"],
    answer: "A",
  },
  {
    id: 64,
    marks: 1,
    type: "MCQ",
    question: "Let \\( f: \\big(\\frac{-\\pi}{2}, \\frac{\\pi}{2} \\big) \\rightarrow \\) : be given by \\( f(x)= \\frac{\\pi}{2} +x-\\text { tan }^{-1} x. \\) Consider the following statements:\n\n\\( P: |f(x)-f(y)| < |x-y| \\text { for all } x.y \\epsilon \\big(\\frac{-\\pi}{2}, \\frac{\\pi}{2} \\big) \\)\n\n\\( Q: f \\) has a fixed point. Then",
    options: ["both P and Q are TRUE.", "Pis TRUE and Q is FALSE.", "P FALSE and Q 15 TRUE.", "both P and Q are FALSE."],
    answer: "D",
  },
  {
    id: 65,
    marks: 1,
    type: "MCQ",
    question: "Let \\(d_{1} \\text{ and } d_{2}\\) denote the usual metric and the discrete metric on R, respectively. Let f: (R, \\(d_{1}\\)) → (R, \\(d_{2}\\)) be defined by \\(f(x) = x, x \\in\\) R. Then",
    options: ["f is continuous but f \\(^{-1}\\) is NOT continuous", "f \\(^{-1}\\) is continuous but f is NOT continuous", "both f and f \\(^{-1}\\) are continuous -1", "neither f nor f \\(^{-1}\\) is continuous"],
    answer: "B",
  },
];

export default test06Questions;
